services:

  app:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    ports:  
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:17.4
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-test}
      POSTGRES_USER: ${POSTGRES_USER:-test}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-test}
    volumes:
      - db:/data/postgresql/
    ports:
      - "5433:5432"

volumes:
  db:

