services:

  app:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.dev
    env_file:
      - .env
    ports:  
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

  db:
    image: postgres:17.4
    env_file:
      - .env
    volumes:
      - db:/data/postgresql/
    command: ["postgres", "-c", "log_statement=all"]

volumes:
  db:

