x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: '12m'
      max-file: '5'

services:

  app:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    ports:  
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    <<: *logging
  db:
    image: postgres:17.4
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    <<: *logging
volumes:
  db:

