services:

  app:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    ports:  
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:17.4
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db:/data/postgresql/

volumes:
  db:

