services:

  app:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    ports:  
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:17.4
    env_file:
      - .env
    volumes:
      - db:/data/postgresql/

volumes:
  db:

